# Nordic theme for Kitty
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic
font_size 12

foreground #cdd6f4
background #1e1e2e
selection_foreground #1e1e2e
selection_background #89dceb

url_color #89b4fa
cursor #cdd6f4
cursor_text_color #1e1e2e

# Black
color0 #313244
color8 #585b70

# Red
color1 #f38ba8
color9 #f38ba8

# Green
color2  #a6e3a1
color10 #a6e3a1

# Yellow
color3  #f9e2af
color11 #f9e2af

# Blue
color4  #89b4fa
color12 #89b4fa

# Magenta
color5  #cba6f7
color13 #cba6f7

# Cyan
color6  #89dceb
color14 #94e2d5

# White
color7  #bac2de
color15 #a6adc8

active_border_color #89dceb
inactive_border_color #585b70
bell_border_color #f9e2af

window_margin_width 4
window_padding_width 2

confirm_os_window_close 0

enable_audio_bell no

shell .
